import type { Resource, BlogPost, Testimonial, NavigationItem, Stat } from '@/types';

export const siteConfig = {
  name: 'DavideGPT',
  tagline: 'Master AI. Own Your Future.',
  description:
    'Learn how to use AI tools like ChatGPT, Claude, and Gemini to save time, create better content, and stay ahead in your career — practical, no-fluff AI education from Davide.',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://davidegpt.ai',
  email: 'hello@davidegpt.ai',
  social: {
    youtube: 'https://youtube.com/@davidegpt',
    instagram: 'https://instagram.com/davidegpt',
    tiktok: 'https://tiktok.com/@davidegpt',
    twitter: 'https://twitter.com/davidegpt',
    linkedin: 'https://linkedin.com/in/davidegpt',
  },
  calendly: process.env.NEXT_PUBLIC_CALENDLY_URL ?? 'https://calendly.com/davidegpt/30min',
};

export const navigation: NavigationItem[] = [
  { label: 'Home', href: '/' },
  {
    label: 'Resources',
    href: '/resources',
    children: [
      { label: 'All Resources', href: '/resources' },
      { label: 'ChatGPT Guides', href: '/resources?category=ChatGPT' },
      { label: 'Prompt Packs', href: '/resources?category=Prompt+Packs' },
      { label: 'AI Toolkits', href: '/resources?category=Toolkits' },
      { label: 'Video Tutorials', href: '/resources?category=Videos' },
    ],
  },
  { label: 'Blog', href: '/blog' },
  { label: 'About', href: '/about' },
  { label: 'Community', href: '/community' },
  { label: 'Contact', href: '/contact' },
];

export const stats: Stat[] = [
  { value: '35', suffix: 'K+', label: 'Followers Worldwide' },
  { value: '50', suffix: '+', label: 'Free Resources' },
  { value: '5', suffix: 'K+', label: 'Newsletter Subscribers' },
  { value: '2022', suffix: '', label: 'Teaching AI Since' },
];

export const resources: Resource[] = [
  {
    slug: 'ultimate-chatgpt-prompting-guide',
    title: 'The Ultimate ChatGPT Prompting Guide',
    description:
      'Master the art of AI prompting with 100+ proven prompt templates for productivity, content creation, coding, and business.',
    category: 'ChatGPT',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    downloadCount: 12400,
    tags: ['ChatGPT', 'Prompts', 'Productivity'],
    featured: true,
    publishedAt: '2024-01-15',
  },
  {
    slug: 'ai-content-creation-toolkit',
    title: 'AI Content Creation Toolkit',
    description:
      'A complete system for creating high-quality blog posts, social media content, and email campaigns with AI in half the time.',
    category: 'Toolkits',
    level: 'Intermediate',
    type: 'Toolkit',
    isFree: false,
    price: 27,
    thumbnail: '',
    downloadCount: 3800,
    tags: ['Content', 'Marketing', 'AI Tools'],
    featured: true,
    publishedAt: '2024-02-01',
  },
  {
    slug: 'claude-ai-beginner-guide',
    title: 'Claude AI: The Complete Beginner\'s Guide',
    description:
      'Everything you need to know about Anthropic\'s Claude — features, use cases, prompt techniques, and real-world examples.',
    category: 'Claude',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    downloadCount: 8200,
    tags: ['Claude', 'Anthropic', 'Beginner'],
    featured: true,
    publishedAt: '2024-02-20',
  },
  {
    slug: 'ai-productivity-workflow-templates',
    title: '20 AI Productivity Workflow Templates',
    description:
      'Ready-to-use AI workflow templates that automate your most repetitive tasks and reclaim 10+ hours per week.',
    category: 'Productivity',
    level: 'Intermediate',
    type: 'Template',
    isFree: false,
    price: 19,
    thumbnail: '',
    downloadCount: 2100,
    tags: ['Productivity', 'Automation', 'Workflows'],
    publishedAt: '2024-03-05',
  },
  {
    slug: 'chatgpt-for-business-owners',
    title: 'ChatGPT for Business Owners',
    description:
      'Learn how to leverage AI to grow your business — from customer support to marketing, operations, and sales.',
    category: 'Business',
    level: 'Intermediate',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    downloadCount: 6700,
    tags: ['Business', 'ChatGPT', 'Entrepreneur'],
    publishedAt: '2024-03-18',
  },
  {
    slug: 'top-50-ai-tools-2024',
    title: 'Top 50 AI Tools You Need to Know',
    description:
      'The definitive guide to the best AI tools for creators, marketers, developers, and business professionals in 2024.',
    category: 'Tools',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    downloadCount: 18900,
    tags: ['AI Tools', 'Resources', 'Directory'],
    featured: true,
    publishedAt: '2024-01-08',
  },
  // Prompt Packs
  {
    slug: 'content-creator-prompt-pack',
    title: '50 Content Creation Prompts for Creators',
    description:
      'Fifty battle-tested prompts for writing viral social posts, YouTube scripts, newsletters, blog articles, and more — ready to copy and paste.',
    category: 'Prompt Packs',
    level: 'Beginner',
    type: 'Prompt Pack',
    isFree: true,
    thumbnail: '',
    downloadCount: 9100,
    tags: ['Prompts', 'Content', 'Social Media'],
    featured: true,
    publishedAt: '2024-02-05',
  },
  {
    slug: 'business-email-prompt-pack',
    title: '30 Business Email Prompts That Get Responses',
    description:
      'Cold outreach, follow-ups, proposals, client updates — 30 proven email prompts that cut writing time and increase reply rates.',
    category: 'Prompt Packs',
    level: 'Beginner',
    type: 'Prompt Pack',
    isFree: true,
    thumbnail: '',
    downloadCount: 6400,
    tags: ['Prompts', 'Email', 'Business'],
    publishedAt: '2024-02-25',
  },
  {
    slug: 'productivity-prompt-pack',
    title: '25 AI Prompts to Automate Your Workday',
    description:
      'Prompts for scheduling, task prioritization, meeting summaries, decision-making, and daily planning — reclaim 2 hours every day.',
    category: 'Prompt Packs',
    level: 'Beginner',
    type: 'Prompt Pack',
    isFree: true,
    thumbnail: '',
    downloadCount: 5200,
    tags: ['Prompts', 'Productivity', 'Automation'],
    publishedAt: '2024-03-10',
  },
  // Toolkits
  {
    slug: 'ai-social-media-toolkit',
    title: 'AI Social Media Toolkit for Creators',
    description:
      'A complete creator toolkit: platform-specific content systems, repurposing frameworks, caption templates, and growth strategies powered by AI.',
    category: 'Toolkits',
    level: 'Intermediate',
    type: 'Toolkit',
    isFree: true,
    thumbnail: '',
    downloadCount: 4700,
    tags: ['Social Media', 'Creators', 'Content'],
    publishedAt: '2024-03-01',
  },
  {
    slug: 'ai-freelancer-toolkit',
    title: 'The AI Freelancer Toolkit',
    description:
      'Everything a freelancer needs to win more clients and deliver better work: proposal templates, client onboarding, pricing strategies, and AI-powered service delivery.',
    category: 'Toolkits',
    level: 'Intermediate',
    type: 'Toolkit',
    isFree: true,
    thumbnail: '',
    downloadCount: 3300,
    tags: ['Freelance', 'Business', 'AI Tools'],
    publishedAt: '2024-03-20',
  },
  {
    slug: 'ai-business-automation-toolkit',
    title: 'AI Business Automation Toolkit',
    description:
      'Automate your marketing, customer service, lead gen, and operations with step-by-step AI playbooks built for small business owners.',
    category: 'Toolkits',
    level: 'Advanced',
    type: 'Toolkit',
    isFree: false,
    price: 29,
    thumbnail: '',
    downloadCount: 2100,
    tags: ['Business', 'Automation', 'AI Tools'],
    publishedAt: '2024-04-01',
  },
  // Videos
  {
    slug: 'chatgpt-masterclass-video',
    title: 'ChatGPT Masterclass: Zero to Pro',
    description:
      'A complete video walkthrough taking you from first login to advanced prompting — covers GPT-4, custom instructions, plugins, and real workflow examples.',
    category: 'Videos',
    level: 'Beginner',
    type: 'Video',
    isFree: true,
    thumbnail: '',
    downloadCount: 22000,
    tags: ['ChatGPT', 'Beginner', 'Video'],
    featured: true,
    publishedAt: '2024-01-20',
  },
  {
    slug: 'prompt-engineering-video-course',
    title: 'Prompt Engineering Crash Course (Video)',
    description:
      'Learn the exact frameworks Davide uses to get professional-grade output from any AI model — includes live examples and reusable templates.',
    category: 'Videos',
    level: 'Intermediate',
    type: 'Video',
    isFree: true,
    thumbnail: '',
    downloadCount: 14500,
    tags: ['Prompts', 'Video', 'Technique'],
    publishedAt: '2024-02-15',
  },
  {
    slug: 'ai-tools-2024-video',
    title: 'Best AI Tools of 2026 — Full Breakdown',
    description:
      'Davide\'s annual video roundup of the most important AI tools — what they do, how to use them, and which ones are actually worth your time.',
    category: 'Videos',
    level: 'Beginner',
    type: 'Video',
    isFree: true,
    thumbnail: '',
    downloadCount: 31000,
    tags: ['AI Tools', 'Video', 'Overview'],
    publishedAt: '2024-01-05',
  },
  // Additional ChatGPT Guides
  {
    slug: 'chatgpt-for-students',
    title: 'ChatGPT for Students: Study Smarter With AI',
    description:
      'How to use ChatGPT for essays, research, exam prep, and understanding complex topics — without cheating or cutting corners.',
    category: 'ChatGPT',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['ChatGPT', 'Students', 'Education'],
    publishedAt: '2024-04-10',
  },
  {
    slug: 'chatgpt-custom-instructions-guide',
    title: 'Custom Instructions for ChatGPT: The Setup Guide',
    description:
      'Set up ChatGPT custom instructions once and get better, more personalised responses every single time — without repeating yourself.',
    category: 'ChatGPT',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['ChatGPT', 'Setup', 'Productivity'],
    publishedAt: '2024-04-18',
  },
  {
    slug: 'chatgpt-for-job-seekers',
    title: 'ChatGPT for Job Seekers: CV, Interviews & More',
    description:
      'Use AI to write a standout CV, tailor cover letters for each role, prep for interviews, and negotiate your salary with confidence.',
    category: 'ChatGPT',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['ChatGPT', 'Career', 'Job Search'],
    publishedAt: '2024-05-01',
  },
  {
    slug: 'chatgpt-writing-guide',
    title: 'Using ChatGPT as Your Personal Writing Coach',
    description:
      'Improve your writing for work, social media, or personal projects — with AI techniques that refine, edit, and help you find your voice.',
    category: 'ChatGPT',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['ChatGPT', 'Writing', 'Copywriting'],
    publishedAt: '2024-05-12',
  },
  {
    slug: 'chatgpt-plugins-gpts-guide',
    title: 'ChatGPT GPTs: How to Find and Use the Best Ones',
    description:
      'A practical guide to the GPT Store — the best custom GPTs for productivity, writing, coding, and research, and how to build your own.',
    category: 'ChatGPT',
    level: 'Intermediate',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['ChatGPT', 'GPTs', 'Tools'],
    publishedAt: '2024-05-20',
  },
  {
    slug: 'ai-for-teachers-guide',
    title: 'AI for Teachers: Save Hours on Lesson Planning',
    description:
      'How teachers and educators can use ChatGPT to plan lessons, create quizzes, write reports, and give better student feedback in less time.',
    category: 'ChatGPT',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['ChatGPT', 'Education', 'Teachers'],
    publishedAt: '2024-06-01',
  },
  {
    slug: 'ai-newsletter-writing-guide',
    title: 'Write Better Newsletters With AI',
    description:
      'A step-by-step guide to using AI to write newsletters people actually read — covering structure, subject lines, tone, and consistency.',
    category: 'ChatGPT',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['ChatGPT', 'Newsletter', 'Writing'],
    publishedAt: '2024-06-10',
  },
  // Additional Prompt Packs
  {
    slug: 'freelancer-pitch-prompt-pack',
    title: '20 Freelancer Pitch & Proposal Prompts',
    description:
      'Stop losing clients to poor pitches. These 20 prompts help you write winning proposals, outreach messages, and follow-ups that convert.',
    category: 'Prompt Packs',
    level: 'Beginner',
    type: 'Prompt Pack',
    isFree: true,
    thumbnail: '',
    tags: ['Prompts', 'Freelance', 'Business'],
    publishedAt: '2024-04-05',
  },
  {
    slug: 'social-media-growth-prompts',
    title: '30 Social Media Growth Prompts',
    description:
      'Grow your audience on Instagram, TikTok, LinkedIn, and YouTube with 30 proven AI prompts for hooks, captions, and content strategies.',
    category: 'Prompt Packs',
    level: 'Beginner',
    type: 'Prompt Pack',
    isFree: true,
    thumbnail: '',
    tags: ['Prompts', 'Social Media', 'Growth'],
    publishedAt: '2024-04-15',
  },
  {
    slug: 'resume-cover-letter-prompts',
    title: '15 Resume & Cover Letter AI Prompts',
    description:
      'Get interview-ready with AI. These 15 prompts help you write a polished resume, tailor cover letters, and stand out from other applicants.',
    category: 'Prompt Packs',
    level: 'Beginner',
    type: 'Prompt Pack',
    isFree: true,
    thumbnail: '',
    tags: ['Prompts', 'Career', 'CV'],
    publishedAt: '2024-05-05',
  },
  {
    slug: 'youtube-script-prompts',
    title: '25 YouTube Script Prompts That Hook Viewers',
    description:
      'Never stare at a blank page again. 25 prompts for writing YouTube scripts with strong hooks, clear structure, and CTAs that convert.',
    category: 'Prompt Packs',
    level: 'Beginner',
    type: 'Prompt Pack',
    isFree: true,
    thumbnail: '',
    tags: ['Prompts', 'YouTube', 'Scripts'],
    publishedAt: '2024-05-15',
  },
  {
    slug: 'sales-persuasion-prompt-pack',
    title: '20 Sales & Persuasion AI Prompts',
    description:
      'Close more deals with AI-crafted sales copy, objection handlers, follow-up sequences, and persuasive scripts for any industry.',
    category: 'Prompt Packs',
    level: 'Intermediate',
    type: 'Prompt Pack',
    isFree: true,
    thumbnail: '',
    tags: ['Prompts', 'Sales', 'Persuasion'],
    publishedAt: '2024-06-05',
  },
  {
    slug: 'midjourney-prompt-pack',
    title: '50 Midjourney Prompts for Creators',
    description:
      'Generate stunning AI images with these 50 Midjourney prompts — covering portraits, product shots, landscapes, brand visuals, and more.',
    category: 'Prompt Packs',
    level: 'Beginner',
    type: 'Prompt Pack',
    isFree: true,
    thumbnail: '',
    tags: ['Prompts', 'Midjourney', 'Image Generation'],
    publishedAt: '2024-06-15',
  },
  // Additional Toolkits
  {
    slug: 'ai-research-toolkit',
    title: 'AI Research & Fact-Finding Toolkit',
    description:
      'Use AI to research topics faster, verify information, summarise long documents, and produce well-sourced reports in a fraction of the time.',
    category: 'Toolkits',
    level: 'Beginner',
    type: 'Toolkit',
    isFree: true,
    thumbnail: '',
    tags: ['Research', 'Productivity', 'AI Tools'],
    publishedAt: '2024-04-20',
  },
  {
    slug: 'ai-student-toolkit',
    title: 'The AI Student Toolkit',
    description:
      'Everything a student needs to succeed with AI: study aids, writing tools, research frameworks, and focus techniques for academic success.',
    category: 'Toolkits',
    level: 'Beginner',
    type: 'Toolkit',
    isFree: true,
    thumbnail: '',
    tags: ['Education', 'Students', 'Productivity'],
    publishedAt: '2024-05-08',
  },
  {
    slug: 'ai-writing-toolkit',
    title: 'AI Writing Toolkit: From Blank Page to Polished Copy',
    description:
      'A complete writing system powered by AI: ideation, drafting, editing, and formatting — for blog posts, emails, social content, and reports.',
    category: 'Toolkits',
    level: 'Intermediate',
    type: 'Toolkit',
    isFree: true,
    thumbnail: '',
    tags: ['Writing', 'Copywriting', 'AI Tools'],
    publishedAt: '2024-05-25',
  },
  // Additional Videos
  {
    slug: 'claude-tutorial-video',
    title: 'Claude AI Full Tutorial — From Beginner to Pro',
    description:
      'A comprehensive video walkthrough of Claude AI: how to set it up, what it does better than ChatGPT, and real use-case demonstrations.',
    category: 'Videos',
    level: 'Beginner',
    type: 'Video',
    isFree: true,
    thumbnail: '',
    tags: ['Claude', 'Beginner', 'Video'],
    publishedAt: '2024-04-12',
  },
  {
    slug: 'midjourney-beginners-video',
    title: 'Midjourney for Beginners — Complete Video Guide',
    description:
      'Learn how to generate professional AI images with Midjourney from scratch — covers prompting, styles, aspect ratios, and v6 features.',
    category: 'Videos',
    level: 'Beginner',
    type: 'Video',
    isFree: true,
    thumbnail: '',
    tags: ['Midjourney', 'Images', 'Video'],
    publishedAt: '2024-04-25',
  },
  {
    slug: 'ai-beginners-full-course-video',
    title: 'AI for Absolute Beginners: The Complete Video Course',
    description:
      'Start from zero and understand exactly how AI works, what tools to use, and how to apply them in your daily life — no tech skills needed.',
    category: 'Videos',
    level: 'Beginner',
    type: 'Video',
    isFree: true,
    thumbnail: '',
    tags: ['Beginner', 'AI Tools', 'Video'],
    featured: true,
    publishedAt: '2024-03-28',
  },
  {
    slug: 'chatgpt-vs-claude-video',
    title: 'ChatGPT vs Claude vs Gemini — Full Comparison Video',
    description:
      'Davide puts the three biggest AI models head to head on writing, reasoning, coding, and creative tasks. See which one wins — and when to use each.',
    category: 'Videos',
    level: 'Beginner',
    type: 'Video',
    isFree: true,
    thumbnail: '',
    tags: ['ChatGPT', 'Claude', 'Gemini', 'Video'],
    publishedAt: '2024-03-15',
  },
  // Additional Claude Guides
  {
    slug: 'claude-vs-chatgpt-comparison',
    title: 'Claude vs ChatGPT: The Honest Breakdown',
    description:
      'A practical, no-hype comparison of Claude and ChatGPT — strengths, weaknesses, pricing, and the exact situations where each one wins.',
    category: 'Claude',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['Claude', 'ChatGPT', 'Comparison'],
    publishedAt: '2024-04-08',
  },
  {
    slug: 'claude-advanced-guide',
    title: 'Advanced Claude Techniques: Get Pro-Level Results',
    description:
      'Go beyond basic prompts. Learn Claude\'s document analysis, long-context capabilities, system prompts, and advanced use cases for professionals.',
    category: 'Claude',
    level: 'Advanced',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['Claude', 'Advanced', 'Techniques'],
    publishedAt: '2024-05-18',
  },
  // Additional Productivity Guides
  {
    slug: 'ai-morning-routine-guide',
    title: 'Build an AI-Powered Morning Routine',
    description:
      'Start every day ahead. Use AI to summarise the news, plan your day, prep key decisions, and enter your work hours ready to focus.',
    category: 'Productivity',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['Productivity', 'Daily Habits', 'AI Tools'],
    publishedAt: '2024-04-22',
  },
  {
    slug: 'ai-meeting-notes-guide',
    title: 'AI for Meeting Notes & Summaries',
    description:
      'Never miss a follow-up again. Use AI to transcribe, summarise, extract action items, and draft follow-up emails from any meeting.',
    category: 'Productivity',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['Productivity', 'Meetings', 'Automation'],
    publishedAt: '2024-05-10',
  },
  {
    slug: 'ai-note-taking-guide',
    title: 'AI Note-Taking: The System That Actually Works',
    description:
      'Build a second brain with AI. Capture, organise, and retrieve your notes and ideas using Notion AI, Claude, and ChatGPT together.',
    category: 'Productivity',
    level: 'Intermediate',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['Productivity', 'Notes', 'Organisation'],
    publishedAt: '2024-05-28',
  },
  // Additional Business Guides
  {
    slug: 'ai-marketing-strategy-guide',
    title: 'Build Your AI Marketing Strategy in a Weekend',
    description:
      'Create a 90-day marketing plan, social content system, email sequences, and ad copy using AI — even if you have no marketing background.',
    category: 'Business',
    level: 'Intermediate',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['Business', 'Marketing', 'Strategy'],
    publishedAt: '2024-04-30',
  },
  {
    slug: 'ai-customer-support-guide',
    title: 'AI Customer Support Playbook for Small Businesses',
    description:
      'Set up AI-powered support that responds instantly, handles FAQs, and escalates the right issues — without hiring more staff.',
    category: 'Business',
    level: 'Intermediate',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['Business', 'Customer Support', 'Automation'],
    publishedAt: '2024-05-22',
  },
  {
    slug: 'ai-sales-automation-guide',
    title: 'Automate Your Sales Pipeline With AI',
    description:
      'From lead gen to close: use AI to write cold outreach, follow-up sequences, proposal drafts, and objection responses that convert.',
    category: 'Business',
    level: 'Intermediate',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['Business', 'Sales', 'Automation'],
    publishedAt: '2024-06-03',
  },
  {
    slug: 'ai-linkedin-growth-guide',
    title: 'AI-Powered LinkedIn Growth Guide',
    description:
      'Grow your professional brand on LinkedIn with AI: optimise your profile, write posts that get traction, and attract the right connections.',
    category: 'Business',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['LinkedIn', 'Personal Brand', 'AI Tools'],
    publishedAt: '2024-06-12',
  },
  {
    slug: 'ai-ecommerce-guide',
    title: 'AI for E-commerce: Products, Marketing & Support',
    description:
      'Use AI to write product descriptions, run paid ad campaigns, handle customer queries, and grow an online store faster than your competitors.',
    category: 'Business',
    level: 'Intermediate',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['E-commerce', 'Business', 'Marketing'],
    publishedAt: '2024-06-20',
  },
  // Additional Tool Guides
  {
    slug: 'ai-image-tools-guide',
    title: 'Best AI Image Generation Tools of 2026',
    description:
      'Midjourney, DALL-E 3, Stable Diffusion, Ideogram — a practical breakdown of each tool, what it does best, and when to use which one.',
    category: 'Tools',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['AI Tools', 'Image Generation', 'Overview'],
    publishedAt: '2024-04-07',
  },
  {
    slug: 'ai-writing-tools-comparison',
    title: 'AI Writing Tools Compared: Which One Is Right for You?',
    description:
      'ChatGPT, Claude, Jasper, Copy.ai — a clear comparison of the top AI writing tools by use case, price, and quality of output.',
    category: 'Tools',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['AI Tools', 'Writing', 'Comparison'],
    publishedAt: '2024-04-28',
  },
  {
    slug: 'best-free-ai-tools-guide',
    title: 'The Best Free AI Tools for Beginners (2026 Edition)',
    description:
      'You don\'t need to spend a penny to start using AI. This guide covers the best free AI tools available today and exactly what to use them for.',
    category: 'Tools',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    featured: true,
    tags: ['AI Tools', 'Free', 'Beginner'],
    publishedAt: '2024-05-03',
  },
  {
    slug: 'notion-ai-complete-guide',
    title: 'Notion AI: The Complete Guide for Beginners',
    description:
      'Everything you need to know about Notion AI — how to use it to write, summarise, translate, and organise your entire workspace.',
    category: 'Tools',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['Notion', 'AI Tools', 'Productivity'],
    publishedAt: '2024-05-16',
  },
  {
    slug: 'perplexity-ai-guide',
    title: 'Perplexity AI: The Search Engine That Cites Its Sources',
    description:
      'Stop Googling. Perplexity AI gives you real-time answers with citations. Learn how to use it for research, fact-checking, and staying informed.',
    category: 'Tools',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['Perplexity', 'Research', 'AI Tools'],
    publishedAt: '2024-05-30',
  },
  {
    slug: 'ai-video-creation-guide',
    title: 'AI Video Creation Tools: Complete Beginner\'s Guide',
    description:
      'Create professional-looking videos with AI — covers Runway, Pika, Sora, HeyGen, and how to pick the right tool for your specific project.',
    category: 'Tools',
    level: 'Beginner',
    type: 'Guide',
    isFree: true,
    thumbnail: '',
    tags: ['AI Tools', 'Video', 'Creation'],
    publishedAt: '2024-06-08',
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: 'how-to-use-chatgpt-for-content-creation',
    title: 'How to Use ChatGPT for Content Creation in 2024',
    excerpt:
      'Discover the exact system I use to create a month of content in a single afternoon using ChatGPT prompts and workflows.',
    category: 'Content Creation',
    thumbnail: '',
    publishedAt: '2024-03-20',
    readTime: '7 min read',
    tags: ['ChatGPT', 'Content', 'Social Media'],
    featured: true,
    author: { name: 'Davide DeMango', avatar: '' },
  },
  {
    slug: 'claude-vs-chatgpt-which-is-better',
    title: 'Claude vs ChatGPT: Which AI is Better in 2024?',
    excerpt:
      'I tested both for 30 days straight. Here\'s an honest breakdown of strengths, weaknesses, and when to use each.',
    category: 'AI Comparison',
    thumbnail: '',
    publishedAt: '2024-03-12',
    readTime: '10 min read',
    tags: ['Claude', 'ChatGPT', 'Comparison'],
    featured: true,
    author: { name: 'Davide DeMango', avatar: '' },
  },
  {
    slug: '10-ai-tools-that-save-10-hours-per-week',
    title: '10 AI Tools That Save Me 10+ Hours Every Week',
    excerpt:
      'These are the exact AI tools I use daily to automate repetitive work and focus on high-leverage tasks.',
    category: 'Productivity',
    thumbnail: '',
    publishedAt: '2024-03-05',
    readTime: '5 min read',
    tags: ['Productivity', 'AI Tools', 'Automation'],
    author: { name: 'Davide DeMango', avatar: '' },
  },
  {
    slug: 'prompt-engineering-for-beginners',
    title: 'Prompt Engineering for Beginners: The Complete Guide',
    excerpt:
      'Learn the fundamentals of writing better AI prompts that get better results every single time.',
    category: 'Prompting',
    thumbnail: '',
    publishedAt: '2024-02-28',
    readTime: '12 min read',
    tags: ['Prompts', 'Beginner', 'Technique'],
    author: { name: 'Davide DeMango', avatar: '' },
  },
  {
    slug: 'how-to-make-money-with-ai',
    title: 'How to Make Money with AI in 2024 (Realistic Guide)',
    excerpt:
      'A realistic, no-hype breakdown of the actual ways people are monetizing AI skills right now.',
    category: 'Business',
    thumbnail: '',
    publishedAt: '2024-02-19',
    readTime: '9 min read',
    tags: ['Business', 'Income', 'AI Skills'],
    author: { name: 'Davide DeMango', avatar: '' },
  },
  {
    slug: 'gemini-vs-chatgpt-google-ai',
    title: 'Google Gemini vs ChatGPT: The Real Comparison',
    excerpt:
      'Google\'s AI has evolved fast. Here\'s where Gemini shines and where ChatGPT still leads.',
    category: 'AI Comparison',
    thumbnail: '',
    publishedAt: '2024-02-10',
    readTime: '8 min read',
    tags: ['Gemini', 'Google', 'ChatGPT'],
    author: { name: 'Davide DeMango', avatar: '' },
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah M.',
    platform: 'Instagram',
    avatar: '',
    quote:
      "Davide's ChatGPT guide changed everything for me. I went from spending 8 hours on content per week to just 2. Absolutely game-changing.",
    role: 'Content Creator',
  },
  {
    id: '2',
    name: 'James K.',
    platform: 'Twitter',
    avatar: '',
    quote:
      'I\'ve followed dozens of AI accounts. DavideGPT is the only one where I actually learn something I can use immediately every single time.',
    role: 'Freelance Marketer',
  },
  {
    id: '3',
    name: 'Priya R.',
    platform: 'LinkedIn',
    avatar: '',
    quote:
      'The AI toolkit resources alone are worth 10x what I paid. I use them daily in my agency and my clients are blown away by the results.',
    role: 'Digital Agency Owner',
  },
  {
    id: '4',
    name: 'Tom D.',
    platform: 'Twitter',
    avatar: '',
    quote:
      'Clear, practical, no fluff. Davide explains AI tools better than anyone I\'ve come across online.',
    role: 'Software Developer',
  },
  {
    id: '5',
    name: 'Elena V.',
    platform: 'Google',
    avatar: '',
    quote:
      'I was completely lost with all these AI tools. After going through the free guides, I finally understand how to use them properly. Thank you!',
    role: 'Small Business Owner',
  },
  {
    id: '6',
    name: 'Marcus J.',
    platform: 'Instagram',
    avatar: '',
    quote:
      'The prompt packs alone saved me hours of trial and error. If you\'re serious about AI, follow DavideGPT.',
    role: 'Marketing Manager',
  },
];

export const faqItems = [
  {
    question: 'Do I need any technical background to learn from DavideGPT?',
    answer:
      'Absolutely not. All resources are designed for complete beginners. If you can use a smartphone, you can follow along. Davide breaks down every concept into simple, actionable steps anyone can understand.',
  },
  {
    question: 'Are your resources really free?',
    answer:
      'Yes — the majority of our resources are completely free. We believe AI education should be accessible to everyone. Some advanced toolkits and premium guides are paid, but there\'s a huge library of free content to start with.',
  },
  {
    question: 'What AI tools do you cover?',
    answer:
      'We cover all major AI tools including ChatGPT, Claude, Google Gemini, Midjourney, DALL-E, Perplexity, Notion AI, and dozens more. We also provide updated guides as new tools launch.',
  },
  {
    question: 'How often is new content published?',
    answer:
      'New free resources, guides, and blog posts are published weekly. Newsletter subscribers get early access to new resources plus exclusive AI tips not published anywhere else.',
  },
  {
    question: 'Can I use these resources for my business?',
    answer:
      'Yes! All resources include commercial use rights for personal and professional purposes. Many of our users are entrepreneurs, agency owners, and marketing professionals using these tools to grow their businesses.',
  },
  {
    question: 'What\'s inside the paid toolkits?',
    answer:
      'Paid resources include advanced prompt systems, workflow templates, video walkthroughs, and ongoing updates. They\'re designed for people who want to go deeper than the free guides and implement professional-grade AI workflows.',
  },
];
